-- Execute no Supabase antes do frontend que envia os campos de consentimento.
create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  email text not null,
  nome text,
  whatsapp text,
  tipo_negocio text,
  origem text not null,
  consentimento_em timestamptz not null default now(),
  politica_privacidade_versao text not null default '2026-08-04',
  criado_em timestamptz not null default now()
);

alter table public.leads
  add column if not exists consentimento_em timestamptz not null default now(),
  add column if not exists politica_privacidade_versao text not null default '2026-08-04',
  add column if not exists criado_em timestamptz not null default now();

create unique index if not exists leads_email_unico on public.leads (lower(email));
alter table public.leads enable row level security;
revoke all on table public.leads from anon, authenticated;
grant insert (email, nome, whatsapp, tipo_negocio, origem, consentimento_em, politica_privacidade_versao)
  on table public.leads to anon, authenticated;

drop policy if exists "cadastro público somente para inserção" on public.leads;
create policy "cadastro público somente para inserção"
  on public.leads for insert to anon, authenticated
  with check (
    char_length(trim(email)) between 5 and 320
    and position('@' in email) > 1
    and consentimento_em is not null
    and char_length(politica_privacidade_versao) > 0
  );

comment on table public.leads is
  'Cadastros da lista de espera Digi.IA; leitura restrita a papéis administrativos.';
